projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: bofafnudovaf5pgmx24xocw2ce
        frontend: javascript
        framework: angular
        amplifyJsLibraryVersion: 6
        maxDepth: 2
